### ISSUE TITLE
buildroot error while compile this module

### ISSUE THREAD

**Issue by WuYingzheng** [rockchip-linux/ffmpeg#1]
hi,
when I use buildroot to build the rootfs image I enter this problem: >>>
......
LD	ffmpeg_g
libavcodec/libavcodec.so: undefined reference to `ff_mpeg4_rkmpp_decoder'
......
I fellow your wiki guide step by step, and i didn't how to slove it. Would you help me solve this problem.

**Comment by rkchrome** [comment]
Which SoCs?  rk3288/rk3399/rk3326/pX3se....

**Comment by WuYingzheng** [comment]
@rkchrome     thanks for your quick reply.
SoC is rk3399
I do >>>
source ./envsetup.sh rockchip_rk3399     ....
then>>>
make   ...

**Comment by rkchrome** [comment]
Hmm, that shoud be fine. I can try to repro it, can you refer the below document before? 

https://github.com/rockchip-linux/docs/blob/master/SoC%20platform%20related/RK3399/RK3399_LINUX_SDK_V2.1_20180601%E5%8F%91%E5%B8%83%E8%AF%B4%E6%98%8E.pdf


I think the easy way that's run ./mk-rootfs.sh for building rootfs

**Comment by WuYingzheng** [comment]
@rkchrome thank you. now everything is ok!
