### ISSUE TITLE
Suport Status

### ISSUE THREAD

**Issue by cassianocasagrande** [rockchip-linux/ffmpeg#4]
Hi there, 

I have the following questions about development status:
    What are supported chipsets?
    Are all codecs (h264, h265 vp9) supported?
    Are both encoding and decoding supported?

Thanks in advance

**Comment by DogFive** [comment]
Second this.

This repo has been around for a little while, it's not mentioned as strongly as gstreamer on the official docs. Is there gonna be official support for ffmpeg?

http://opensource.rock-chips.com/wiki_Mpp

**Comment by JeffyCN** [comment]
> What are supported chipsets?
I guess all chips are supported.
> Are all codecs (h264, h265 vp9) supported?
Yes, see libavcodec/rkmppdec.c
> Are both encoding and decoding supported?
The encoding support is limited, requires special format(drm_prime)

And yes, we are recommend to use gstreamer instead of ffmpeg for higher performance and less hacks.
