### ISSUE TITLE
libavutil/hwcontext_drm.c:124:29: error: ‘DRM_FORMAT_NV12_10’ undeclared here (not in a function)

### ISSUE THREAD

**Issue by FreshLuoBoGan** [rockchip-linux/ffmpeg#5]
./configure --enable-static --enable-shared --enable-pthreads --enable-rkmpp --enable-version3 --enable-libdrm

**Comment by FreshLuoBoGan** [comment]
please help me!!!!!!

**Comment by stweiz** [comment]
I also have this issue with the 4.1 release. mpp and aom are compiled by me from the current sources.
I do not cross-compile ffmpeg and its dependencies. I compile them directly on the rock64.

**Comment by gounthar** [comment]
Same here on the OrangePi RK3399.

**Comment by stweiz** [comment]
Thank you for the information @gounthar ! As I read, this is a module for decoding HEVC 10bit streams. So either it won't work with that kind of material or ffmpeg will switch to CPU decoding.
Maybe we can get more information in this chat: https://irclog.whitequark.org/linux-rockchip/2017-02-02
I'll investigate it later. Now I will compile it by ignoring the line ;)

**Comment by ximus** [comment]
got the same here on rockpro64 

ffmpeg: version `589de66a0b50c43b93f511361275d9ff86da21dd`
os: armbian stretch `Linux rockpro64 4.4.182-rockchip64 #1 SMP Fri Jun 28 17:34:00 CEST 2019 aarch64 GNU/Linux`
ffmpeg configure: `./configure --enable-gpl --disable-stripping --enable-libmp3lame --enable-libopenjpeg --enable-omx --enable-libx264 --enable-shared --enable-rkmpp --enable-version3 --enable-nonfree --enable-libdrm --enable-pthreads --enable-static`

i also commented out the line for now

**Comment by stweiz** [comment]
I merged the 4.1 release of this repository with the 4.2 release branch (from 08.08.) of the original ffmpeg project on github. This issue is fixed by ffmpeg as you can also see it in the commits. The build ran fine and the DRM_FORMAT_NV12_10 support is added. But now I see, that the commit is removed from their branch O.o
I will update and test it again. If it works, I will push it in the branch of my fork.

https://github.com/stweiz/ffmpeg/tree/rockchip-ffmpeg-stevog/release/4.2
or gitlab:
https://gitlab.com/stevog/ffmpeg-rockchip/tree/rockchip-ffmpeg-stevog/release/4.2

**Comment by gounthar** [comment]
I test mp4 files this way:

```bash
ffmpeg -benchmark -loglevel 48 -vcodec h264_rkmpp -i bbb_sunflower_1080p_30fps_normal.mp4 -map 0:v:0 -f null -
```

**Comment by kmlebedev** [comment]
Big thanks, someone doesn't really believe https://medium.com/@poddingue/stream-for-cheap-rk3399-and-ffmpeg-part-i-149f330bd127

**Comment by JeffyCN** [comment]
The DRM_FORMAT_NV12_10 is a vendor format, which should be defined in the BSP 4.4 kernel's headers.
So there're multiple ways to fix it:
1/ wrap with ifdef - endif, which is done in the newest release/4.1
2/ add a ifndef - define - endif, for example:
https://github.com/rockchip-linux/gstreamer-rockchip/commit/9987a660d6f53553f9c74c042888eb417833c932

And for the h264_v4l2m2m issue, it's obviously selecting the wrong decoder(v4l2m2m is mostly using on tegra platforms, we do have a v4l2 version of driver, but using v4l2 slice APIs).
There also multiple ways to fix it:
1/ disable other decoders to make the rkmpp the only choice:
https://github.com/JeffyCN/FFmpeg/blob/debian/4.1.4-1/debian/rules#L180
2/ hack to prefer using hw decoders:
https://github.com/rockchip-linux/ffmpeg/commit/7b677a25ac08940b78bf7d24908ae76757c60475
3/ specify it in the cmd as gounthar replied
