### ISSUE TITLE
在rk3399上安装ffmpeg遇到的问题

### ISSUE THREAD

**Issue by zhouzhouzlove** [rockchip-linux/ffmpeg#6]
说明，基于rk3399做了一款开发板，现在需要用到vpu的硬解码功能，打算基于ffmpeg。
现有疑惑如下：

1、我目前只安装了从这里下载的ffmpeg，是否还需要同事下载编译安装mpp?

2、安装ffmpeg时，应该怎么样配置？是否有配置的官方建议？
        目前的配置和安装如下：
         ./configure --enable-shared --prefix=/opt/ffmpeg
        make 
        sudo make install
        但是是否需要打开
        -enable-rkmpp           enable Rockchip Media Process Platform code [no]
        当添加这个选项时，配置报错会说：
        rkmpp is version3 and --enable-version3 is not specified.
         当加上--enable-version3后会报错，pkg-config未安装。
![ffmpeg-rockchip](https://user-images.githubusercontent.com/50945197/63396138-a6d82680-c3f8-11e9-9447-48622728c138.png)

3、我同时安装了从这里下载的ffmpeg（4.0）和从ffmpeg官网下载的ffmpeg（4.1.3），  
        并且分别使用这两个库编译了一个保存rtsp视频流到本地的demo，但是发现cpu占用频率没 
       有区别。
      我认为，瑞芯微对ffmpeg做了修改，那么从ffmpeg官网下载的版本4.1.3就应该表现的更差一 
      点，但是结果却不是这样，这是否意味着我的安装有误？

**Comment by zhouzhouzlove** [comment]
我做了个实验：
1、只安装ffmpeg官网的ffmpeg4.0版本，用自己的程序去测试（解码rtsp流），发现可以软解；
2、只安装瑞芯微的ffmpeg4.0版本，提示无法找到解码器，打开流失败；
3、安装了mpp，同样提示无法找到解码器，打开流失败。

结论如下：我不知道怎么配置ffmpeg和mpp，才能使得ffmpeg可以调用到VPU。
希望官方能够给出一个配置的说明。
报错信息：
命令
./aviRead rtsp://admin:RCTHJC@192.168.1.158/h264/ch1/main/av_stream
输出：
[h264_v4l2m2m @ 0x74ea070] Could not find a valid device
[h264_v4l2m2m @ 0x74ea070] can't configure decoder
Can't open video file rtsp://admin:RCTHJC@192.168.1.158/h264/ch1/main/av_stream

**Comment by stweiz** [comment]
@zhouzhouzlove for configuration and compile instructions for the dependencies (mpp etc.) and ffmpeg, you can visit my repository.

https://github.com/stweiz/ffmpeg/tree/rockchip-ffmpeg-stevog/release/4.2
or gitlab:
https://gitlab.com/stevog/ffmpeg-rockchip/tree/rockchip-ffmpeg-stevog/release/4.2

You can find the information and a link to a tutorial in the README.md

At the end I get the same error as you.

`[h264_v4l2m2m @ 0x5576e79280] Could not find a valid device
[h264_v4l2m2m @ 0x5576e79280] can't configure decoder
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (h264_v4l2m2m) -> h264 (libx264))
  Stream #0:1 -> #0:1 (copy)
Error while opening decoder for input stream #0:0 : Invalid argument`

Let me now, if you have a solution.

**Comment by zhouzhouzlove** [comment]
@stweiz 
Thanks for your help.
I haven't solved this problem yet.
Some other users suggetted me to use MPP directly.

Here is the link.
http://t.rock-chips.com/forum.php?mod=viewthread&tid=336

**Comment by lyvivian0077** [comment]
## 我也是遇到了同样问题,不知道怎么解决.

@stweiz 你解决了? 我是按照你的git里的教程安装的.

```
root@nanopim4:~/backup# ffmpeg   -i isdbt188.ts -c:v h264 out.h264
ffmpeg version 4b0b85f632 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1)
  configuration: --prefix=/opt/ffmpeg/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/opt/ffmpeg/ffmpeg_build/include --extra-ldflags=-L/opt/ffmpeg/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/opt/ffmpeg/ffmpeg_bin --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-rkmpp --enable-version3 --enable-libdrm --enable-libx265 --enable-nonfree
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mpegts @ 0x558acd6580] PES packet size mismatch
Input #0, mpegts, from 'isdbt188.ts':
  Duration: 00:01:00.87, start: 109.851700, bitrate: 17304 kb/s
  Program 23664
    Metadata:
      service_name    : ?ERB?|
      service_provider:
    Stream #0:0[0x200]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(yuv420p) (tv, top first), 1440x1080 [SAR 4:3 DAR 16:9], 16712 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
    Stream #0:1[0x201]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 186 kb/s
File 'out.h264' already exists. Overwrite ? [y/N] y
[mpeg2_v4l2m2m @ 0x558adbaea0] Could not find a valid device
[mpeg2_v4l2m2m @ 0x558adbaea0] can't configure decoder
Stream mapping:
  Stream #0:0 -> #0:0 (mpeg2video (mpeg2_v4l2m2m) -> h264 (h264_rkmpp))
Error while opening decoder for input stream #0:0 : Invalid argument
root@nanopim4:~/backup#
```

**Comment by zhouzhouzlove** [comment]
建议直接用mpp，这个问题没有解决。


 
---原始邮件---
发件人: "lyvivian0077"<notifications@github.com&gt;
发送时间: 2019年12月11日 17:25:58
收件人: "rockchip-linux/ffmpeg"<ffmpeg@noreply.github.com&gt;;
抄送: "zhouzhouzlove"<814614574@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [rockchip-linux/ffmpeg] 在rk3399上安装ffmpeg遇到的问题 (#6)



我也是遇到了同样问题,不知道怎么解决.
 
@stweiz 你解决了? 我是按照你的git里的教程安装的.
 root@nanopim4:~/backup# ffmpeg   -i isdbt188.ts -c:v h264 out.h264 ffmpeg version 4b0b85f632 Copyright (c) 2000-2019 the FFmpeg developers   built with gcc 7 (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1)   configuration: --prefix=/opt/ffmpeg/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/opt/ffmpeg/ffmpeg_build/include --extra-ldflags=-L/opt/ffmpeg/ffmpeg_build/lib --extra-libs='-lpthread -lm' --bindir=/opt/ffmpeg/ffmpeg_bin --enable-gpl --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-rkmpp --enable-version3 --enable-libdrm --enable-libx265 --enable-nonfree   libavutil      56. 31.100 / 56. 31.100   libavcodec     58. 54.100 / 58. 54.100   libavformat    58. 29.100 / 58. 29.100   libavdevice    58.  8.100 / 58.  8.100   libavfilter     7. 57.100 /  7. 57.100   libswscale      5.  5.100 /  5.  5.100   libswresample   3.  5.100 /  3.  5.100   libpostproc    55.  5.100 / 55.  5.100 [mpegts @ 0x558acd6580] PES packet size mismatch Input #0, mpegts, from 'isdbt188.ts':   Duration: 00:01:00.87, start: 109.851700, bitrate: 17304 kb/s   Program 23664     Metadata:       service_name    : ?ERB?|       service_provider:     Stream #0:0[0x200]: Video: mpeg2video (Main) ([2][0][0][0] / 0x0002), yuv420p(yuv420p) (tv, top first), 1440x1080 [SAR 4:3 DAR 16:9], 16712 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc     Stream #0:1[0x201]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 186 kb/s File 'out.h264' already exists. Overwrite ? [y/N] y [mpeg2_v4l2m2m @ 0x558adbaea0] Could not find a valid device [mpeg2_v4l2m2m @ 0x558adbaea0] can't configure decoder Stream mapping:   Stream #0:0 -&gt; #0:0 (mpeg2video (mpeg2_v4l2m2m) -&gt; h264 (h264_rkmpp)) Error while opening decoder for input stream #0:0 : Invalid argument root@nanopim4:~/backup#

**Comment by stweiz** [comment]
@lyvivian0077 I didn't solve it yet. I get the same error as you. I will give it a next try in the next days and will report my result. Also I will try gstreamer. Maybe it's the better solution. I want to use this with jellyfin (emby), which only supports ffmpeg for now. But their code is open source...

**Comment by lyvivian0077** [comment]
@zhouzhouzlove 
谢谢你的回复.
请问有mpp的 `encode` 示范代码么? 本人不会C呀,只会python.
我只想把m2ts 文件转换成MP4,之后在电脑或电视盒子上看.
现在一直用ffmpeg  cpu encode, 非常慢. 费时又费电.

**Comment by lyvivian0077** [comment]
@stweiz 
thankyou for U reply.
If gstreamer is worked, please tell me.

**Comment by JeffyCN** [comment]
The mpeg2_v4l2m2m log means you are using v4l2mem codec, not rkmpp.
The easiest way for this would be try to disable whatever comes between you and the rkmpp, for example:
https://github.com/JeffyCN/FFmpeg/blob/debian/4.1.4-1/debian/rules#L181

And due to the drm_prime frame format, the ffmpeg's rkmpp enc/dec are hard to use for normal users.

So i would recommend using gstreamer instead, the pipeline would be something like:
gst-launch-1.0 uridecodebin uri=file:///test.ts ! mpph264enc ! filesink location=/test.mp4

NOTE:
1/ this only works in the newest version of mpp & gstreamer-rockchip.
2/ you can tweak the encode property to improve the video quality(with higher bitrate), for example:
gst-launch-1.0 uridecodebin uri=file:///test.ts ! mpph264enc rc-mode=fixqp ! filesink location=/test.mp4
