### ISSUE TITLE
Will we get h.264 hardware encoding on RK3399 next year?

### ISSUE THREAD

**Issue by gounthar** [rockchip-linux/ffmpeg#9]
Hi team,

first, thanks a lot for your work. I managed to compile your fork of ffmpeg on my OrangePi RK3399, and use hardware decoding.
Now, I need to hardware encode h.264 coming from the HDMI-IN, so I'd like to know when/if hardware decoding will be available, so that I can buy more RK3399-based boards or just abandon the project.

Thanks.

**Comment by gounthar** [comment]
I saw in your roadmap on the wiki that it was scheduled for Q4 2019.

**Comment by facontidavide** [comment]
Any update?

**Comment by Hong123123** [comment]
Any update?

**Comment by JeffyCN** [comment]
https://github.com/rockchip-linux/ffmpeg/commit/6c43f88bc5cdf666229c95ab60de1e7354cd7f52
